In [1]:
import torch
import numpy as np

### Array to Tensor

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.dtype

dtype('int64')

In [7]:
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5])

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
x.dtype

torch.int64

In [11]:
arr2d = np.arange(0.0, 12.0).reshape(4,3)

In [12]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [13]:
x2 = torch.from_numpy(arr2d)

In [14]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
x

tensor([1, 2, 3, 4, 5])

In [17]:
arr[0] =  99

In [18]:
x

tensor([99,  2,  3,  4,  5])

`from_numpy()` creates a direct link

In [19]:
new_arr = np.arange(0,10)

In [20]:
new_tensor = torch.tensor(new_arr)

In [21]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
new_arr[0] = 99

In [23]:
new_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [24]:
new_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`tensor()` creates a copy

### Constructing Tensor from Scratch

In [25]:
arr = np.array([1,2,3,4])

In [26]:
arr.dtype

dtype('int64')

In [27]:
torch.tensor(arr)

tensor([1, 2, 3, 4])

In [28]:
torch.Tensor(arr)

tensor([1., 2., 3., 4.])

`Tensor()` creates float Tensor. Equivalent to `FloatTensor()`

In [32]:
torch.empty(2,2) # Allocate a block of memory

tensor([[1.5205e-21, 3.1965e-41],
        [2.1522e-04, 4.3865e-41]])

In [33]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
torch.arange(0,9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [39]:
torch.linspace(0,18, 12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [40]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [41]:
my_tensor = torch.tensor([1,2,3])

In [42]:
my_tensor.dtype

torch.int64

In [45]:
my_tensor = my_tensor.type(torch.int32)

In [46]:
my_tensor.dtype

torch.int32

### Getting random values

In [47]:
torch.rand(4,3) # random sample from a uniform distribution between 0 and 1

tensor([[0.9718, 0.1529, 0.7280],
        [0.1000, 0.9333, 0.4824],
        [0.9411, 0.9883, 0.1607],
        [0.1991, 0.8478, 0.5904]])

In [48]:
torch.randn(4, 3) # random smaple from normal distribution

tensor([[-1.4833, -0.4198,  0.6179],
        [-0.6113, -0.1672, -1.0245],
        [ 2.6055, -0.4145,  1.3026],
        [ 0.6457,  0.4183, -0.2675]])

In [50]:
torch.randint(low=10, high=19, size=(5,5))

tensor([[17, 18, 14, 15, 18],
        [12, 13, 14, 16, 15],
        [16, 10, 13, 14, 15],
        [15, 11, 10, 13, 13],
        [16, 12, 11, 10, 13]])

In [51]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [52]:
x.shape

torch.Size([2, 5])

In [54]:
torch.rand_like(x) # Uses the shape of x for the rand matrix

tensor([[0.2792, 0.0845, 0.3661, 0.7552, 0.8524],
        [0.6323, 0.9827, 0.2847, 0.0983, 0.5642]])

In [55]:
torch.randint_like(x, low=0, high=9)

tensor([[3., 8., 1., 4., 5.],
        [4., 3., 5., 0., 6.]])

In [62]:
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [60]:
torch.rand(2,3) # Has to be in the same cell of seed for consistency

tensor([[0.0756, 0.1966, 0.3164],
        [0.4017, 0.1186, 0.8274]])

### Tensor Operations

In [63]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [64]:
type(x[1,1])

torch.Tensor

In [65]:
x[1,1]

tensor(3)

In [68]:
x[:,1] # Indexing

tensor([1, 3, 5])

In [70]:
x[:,1:] # Slicing

tensor([[1],
        [3],
        [5]])

In [71]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [73]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x = x.reshape(2,5)
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [78]:
x = torch.arange(0,10)

In [79]:
z = x.view(2,5)

In [80]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [81]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x[0] = 999

In [83]:
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [85]:
z # is linked to x when created by using view()

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [86]:
x = torch.arange(10)

In [87]:
x.shape

torch.Size([10])

In [88]:
x.view(2, -1) # Pytorch will try to figure out the other dimension

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [102]:
a = torch.tensor([1.,2.,3.])

In [103]:
a

tensor([1., 2., 3.])

In [104]:
b = torch.tensor([3.,4.,5.])

In [105]:
a + b

tensor([4., 6., 8.])

In [106]:
torch.add(a,b)

tensor([4., 6., 8.])

In [107]:
# a = a + b
a.add_(b) # In-place

tensor([4., 6., 8.])

In [108]:
a

tensor([4., 6., 8.])

In [109]:
a.mul_(b)

tensor([12., 24., 40.])

In [110]:
a.dot(b)

tensor(332.)

In [113]:
a = torch.arange(1, 10).reshape(3,3)
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [117]:
b = torch.arange(3, 15).reshape(3, 4)
b

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]])

In [121]:
torch.mm(a,b)

tensor([[ 50,  56,  62,  68],
        [113, 128, 143, 158],
        [176, 200, 224, 248]])

In [122]:
a @ b

tensor([[ 50,  56,  62,  68],
        [113, 128, 143, 158],
        [176, 200, 224, 248]])

In [120]:
b.shape

torch.Size([3, 4])

In [128]:
x = torch.arange(1.,10)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [130]:
x.norm()

tensor(16.8819)

In [131]:
x.numel()

9

In [132]:
len(x)

9

In [134]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [135]:
len(a)

3

In [137]:
a.numel()

9