In [1]:
import numpy as np

### Arrays

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mymatrix = np.array(mylist)

In [10]:
mymatrix.shape

(3, 3)

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# NumPy allows us to do operations on all the elements of an array but python list does not
np.ones((3, 4)) * 3 + 6

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random functions

In [29]:
# random number from 0 to n from an uniform distribution
np.random.rand(5)

array([0.62448627, 0.6928925 , 0.64349106, 0.57774038, 0.97029723])

In [31]:
# random number from standard normal distribution
np.random.randn(5)

array([-0.29251841, -2.51977847,  0.58960485, -0.00768093, -1.04624131])

In [33]:
np.random.randint(10, 20, 3)

array([10, 10, 17])

In [34]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [35]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr = np.random.randint(0, 30, 10)

In [48]:
ranarr

array([ 5,  1, 27, 20,  0, 11, 25, 21, 28, 11])

In [49]:
ranarr.max()

28

In [50]:
ranarr.min()

0

In [51]:
# index location of max
ranarr.argmax()

8

In [52]:
# index location of min
ranarr.argmin()

4

### Index selection

In [60]:
arr = np.arange(10)

In [61]:
arr[0]

0

In [62]:
arr[0:3]

array([0, 1, 2])

In [63]:
arr[:3]

array([0, 1, 2])

In [64]:
arr[5:]

array([5, 6, 7, 8, 9])

In [66]:
# arr[start:end:increment]
arr[::2]

array([0, 2, 4, 6, 8])

In [68]:
# broadcasting
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [80]:
sliced_array = arr[:4]

In [81]:
sliced_array

array([0, 1, 2, 3])

In [82]:
sliced_array[:] =  10

In [83]:
sliced_array

array([10, 10, 10, 10])

In [84]:
arr

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9])

The operation is broadcasted to the reference array. To avoid that we need to use the `arr.copy()` function

In [85]:
new_slice = arr.copy()

In [86]:
new_slice

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [87]:
new_slice[:] = 100

In [88]:
new_slice

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [89]:
arr

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [90]:
# Indexing 2D Array

In [105]:
arr = np.array([[0, 1, 2], [11, 12, 13], [21, 22, 23]])

In [106]:
arr

array([[ 0,  1,  2],
       [11, 12, 13],
       [21, 22, 23]])

In [107]:
arr.shape

(3, 3)

In [108]:
arr[2][2]

23

In [110]:
arr[:2]

array([[ 0,  1,  2],
       [11, 12, 13]])

In [112]:
arr[:2, 1:] # ranges - [:row, col:]

array([[ 1,  2],
       [12, 13]])

In [113]:
arr > 4

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [114]:
bool_array = arr > 4

In [116]:
arr[bool_array] # return array of elements satisfying the boolean condition

array([11, 12, 13, 21, 22, 23])

In [118]:
arr[arr % 2 == 0]

array([ 0,  2, 12, 22])

### Operations

In [119]:
arr = np.arange(0, 10)

In [120]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [122]:
arr / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [123]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [124]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [125]:
arr / 0

/tmp/ipykernel_53697/3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
/tmp/ipykernel_53697/3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [126]:
1/arr

/tmp/ipykernel_53697/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [127]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [128]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [129]:
np.log(arr)

/tmp/ipykernel_53697/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [130]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [131]:
arr.sum()

45

In [132]:
arr.mean()

4.5

In [134]:
arr.std()

2.8722813232690143

In [138]:
arr_2d = np.arange(1, 13).reshape(3, 4)

In [139]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
arr_2d.sum()

78

In [143]:
arr_2d.sum(axis=0) # row sum

array([15, 18, 21, 24])

In [145]:
arr_2d.sum(axis=1) # col sum

array([10, 26, 42])